version: "2"

volumes:
  bolid_nginxproxy_local_nginx_vhost:
    name: bolid_nginxproxy_local_nginx_vhost
  bolid_nginxproxy_local_nginx_html:
    name: bolid_nginxproxy_local_nginx_html
  bolid_nginxproxy_local_nginx_certs:
    name: bolid_nginxproxy_local_nginx_certs
  # bolid_nginxproxy_local_nginx_logs:
  #   name: bolid_nginxproxy_local_nginx_logs

services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: bolid_nginxproxy_local_nginx
    container_name: bolid_nginxproxy_local_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - bolid_nginxproxy_local_nginx_certs:/etc/nginx/certs
      - bolid_nginxproxy_local_nginx_vhost:/etc/nginx/vhost.d
      - bolid_nginxproxy_local_nginx_html:/usr/share/nginx/html
      # - bolid_nginxproxy_local_nginx_logs:/var/log/nginx
      - ./nginxproxy/custom_proxy.conf:/etc/nginx/conf.d/custom_proxy.conf
    networks:
      - bolid_nginxproxy_local_network

networks:
  bolid_nginxproxy_local_network:
    name: bolid_nginxproxy_local_network
