version: "2"

volumes:
  bolid_nginxproxy_production_nginx_vhost:
    name: bolid_nginxproxy_production_nginx_vhost
  bolid_nginxproxy_production_nginx_html:
    name: bolid_nginxproxy_production_nginx_vhost
  bolid_nginxproxy_production_nginx_certs:
    name: bolid_nginxproxy_production_nginx_certs
  bolid_nginxproxy_production_ssl_acme:
    name: bolid_nginxproxy_production_ssl_acme
  # bolid_nginxproxy_production_nginx_logs:
  #   name: bolid_nginxproxy_production_nginx_logs

services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    image: bolid_nginxproxy_production_nginxproxy
    container_name: bolid_nginxproxy_production_nginxproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - bolid_nginxproxy_production_nginx_certs:/etc/nginx/certs
      - bolid_nginxproxy_production_nginx_vhost:/etc/nginx/vhost.d
      - bolid_nginxproxy_production_nginx_html:/usr/share/nginx/html
      # - bolid_nginxproxy_production_nginx_logs:/var/log/nginx/
    networks:
      - bolid_nginxproxy_production_network

  ssl:
    image: nginxproxy/acme-companion:2.1.0
    container_name: bolid_nginxproxy_production_acmecompanion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - bolid_nginxproxy_production_ssl_acme:/etc/acme.sh
    networks:
      - bolid_nginxproxy_production_network

networks:
  bolid_nginxproxy_production_network:
    name: bolid_nginxproxy_production_network
